name: Deployment
on:
  push:
    branches:
       - master

jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
       - name: preparation
         run: echo "preparing to deploy ..."

       - name: check out the repository
         uses: actions/checkout@v4

       - name: Set up Python
         uses: actions/setup-python@v2
         with:
            python-version: '3.8'

       - name: Install pip
         run: |
            python -m ensurepip --upgrade

       - name: Install EB CLI
         run: |
            pip install --upgrade awsebcli

       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
            role-duration-seconds: 1200
            aws-region: ${{ secrets.AWS_REGION }}

       - name: Deploy to Elastic Beanstalk
         run: |
            eb init -p docker 2books --region ${{ secrets.AWS_REGION }}
            eb create testenv

    #    - name: Terminate Elastic Beanstalk
    #      run: |
    #         eb terminate test-env