name: Deployment
on:
  push:
    branches:
       - master

jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
       - name: preparation
         run: echo "preparing to deploy ..."

       - name: check out the repository
         uses: actions/checkout@v4

       - name: Generate deployment package
         run: zip -r deploy.zip . -x '*.git*'

    #    - name: "Logs into docker"
    #      uses: docker/login-action@v3
    #      with:
    #          username: ${{ secrets.DOCKERHUB_USERNAME }}
    #          password: ${{ secrets.DOCKERHUB_PASSWORD }}

    #    - name: "Get the code from Docker Hub"
    #      run: "sudo docker pull epauldike/booksfinder:latest"

    #    - name: Configure AWS Credentials
    #      uses: aws-actions/configure-aws-credentials@v4
    #      with:
    #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #         aws-region: eu-north-1

       - name: Deploy to EB
         uses: einaregilsson/beanstalk-deploy@v22
         with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            application_name: 2books
            environment_name: testenv
            version_label: 12345
            region: eu-north-1
            deployment_package: deploy.zip